name: puxaconversa_app
description: "Puxa-Conversa: um aplicativo de perguntas para iniciar conversas."
publish_to: 'none' 
version: 0.1.0+1 # Lê-se: Nome_da_Versão+Versão_do_Código

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Data
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  # UI
  appinio_swiper: ^2.1.1
  auto_size_text: ^3.0.0
  fading_edge_scrollview: ^4.1.1
  sizer: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  image_path: "assets/images/app-logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app-logo.png"
  adaptive_icon_foreground_inset: 22

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Geomatrix
      fonts:
        - asset: fonts/Geomatrix.otf
    - family: Gnuolane
      fonts:
        - asset: fonts/Gnuolane.otf
    - family: Tendang
      fonts:
        - asset: fonts/Tendang.otf